version: "3.8"

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    #   - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    image: backend-image
    build:
      context: ./back
    networks:
      - dev
    ports:
      - "5000:5000"

  frontend:
    image: frontend-image
    build:
      context: ./front_1
    networks:
      - dev
  bot:
    image: bot-image
    build:
      context: ./bot
    command: ["node", "bot.js"]
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - dev
